# Generated by Django 6.1.1 on 2026-09-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shielddevice',
            old_name='gps_ready',
            new_name='gps_status',
        ),
        migrations.RenameField(
            model_name='shielddevice',
            old_name='gsm_connected',
            new_name='gsm_status',
        ),
        migrations.RenameField(
            model_name='shielddevice',
            old_name='last_communication',
            new_name='last_seen',
        ),
        migrations.RemoveField(
            model_name='safetycontact',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='shielddevice',
            name='last_latitude',
        ),
        migrations.RemoveField(
            model_name='shielddevice',
            name='last_longitude',
        ),
        migrations.RemoveField(
            model_name='shielddevice',
            name='status',
        ),
        migrations.AddField(
            model_name='safetycontact',
            name='relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shielddevice',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyincident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyincident',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual SOS'), ('test', 'Test Emergency'), ('device', 'Device SOS')], default='manual', max_length=20),
        ),
    ]
